import Foundation

// Generated on 5 October 2026 from NJ Transit's live feed: every station on the stop lists of 216
// trains across all lines, with its board name (as stop lists and departure boards name it), its
// lines (board codes) and its trip planner name, each accepted by the live board and planner.

extension Stations {
    /// Every NJ Transit rail station a rider can call home (see `UserConfig.homeId`), plus the
    /// destinations. The four the app has always known keep their own entries (`Stations.all`).
    public static let catalog: [Station] = [
        Station(id: "aberdeenmatawan", name: "Aberdeen-Matawan", plannerName: "Aberdeen Matawan Station", shortLabel: "Aberdeen-Matawan", lines: ["NJCL"]),
        Station(id: "absecon", name: "Absecon", plannerName: "Absecon Station", shortLabel: "Absecon", lines: ["ACRL"]),
        Station(id: "allendale", name: "Allendale", plannerName: "Allendale Station", shortLabel: "Allendale", lines: ["BERG", "MAIN"]),
        Station(id: "allenhurst", name: "Allenhurst", plannerName: "Allenhurst Station", shortLabel: "Allenhurst", lines: ["NJCL"]),
        Station(id: "andersonstreet", name: "Anderson Street", plannerName: "Anderson Street Station", shortLabel: "Anderson Street", lines: ["PASC"]),
        Station(id: "annandale", name: "Annandale", plannerName: "Annandale Station", shortLabel: "Annandale", lines: ["RARV"]),
        Station(id: "asburypark", name: "Asbury Park", plannerName: "Asbury Park Station", shortLabel: "Asbury Park", lines: ["NJCL"]),
        Station(id: "atco", name: "Atco", plannerName: "Atco Station", shortLabel: "Atco", lines: ["ACRL"]),
        Station(id: "atlanticcityrailterminal", name: "Atlantic City Rail Terminal", plannerName: "Atlantic City Rail Terminal", shortLabel: "Atlantic City", lines: ["ACRL"]),
        Station(id: "avenel", name: "Avenel", plannerName: "Avenel Station", shortLabel: "Avenel", lines: ["NJCL"]),
        Station(id: "baskingridge", name: "Basking Ridge", plannerName: "Basking Ridge Station", shortLabel: "Basking Ridge", lines: ["M&E"]),
        Station(id: "bayhead", name: "Bay Head", plannerName: "Bay Head Station", shortLabel: "Bay Head", lines: ["NJCL"]),
        Station(id: "baystreet", name: "Bay Street", plannerName: "Bay Street Station", shortLabel: "Bay Street", lines: ["MOBO"]),
        Station(id: "belmar", name: "Belmar", plannerName: "Belmar Station", shortLabel: "Belmar", lines: ["NJCL"]),
        Station(id: "berkeleyheights", name: "Berkeley Heights", plannerName: "Berkeley Heights Station", shortLabel: "Berkeley Heights", lines: ["M&E"]),
        Station(id: "bernardsville", name: "Bernardsville", plannerName: "Bernardsville Station", shortLabel: "Bernardsville", lines: ["M&E"]),
        Station(id: "bloomfield", name: "Bloomfield", plannerName: "Bloomfield Rail Station", shortLabel: "Bloomfield", lines: ["MOBO"]),
        Station(id: "boonton", name: "Boonton", plannerName: "Boonton Station", shortLabel: "Boonton", lines: ["MOBO"]),
        Station(id: "boundbrook", name: "Bound Brook", plannerName: "Bound Brook Station", shortLabel: "Bound Brook", lines: ["RARV"]),
        Station(id: "bradleybeach", name: "Bradley Beach", plannerName: "Bradley Beach Station", shortLabel: "Bradley Beach", lines: ["NJCL"]),
        Station(id: "brickchurch", name: "Brick Church", plannerName: "Brick Church Station", shortLabel: "Brick Church", lines: ["M&E"]),
        Station(id: "bridgewater", name: "Bridgewater", plannerName: "Bridgewater Station", shortLabel: "Bridgewater", lines: ["RARV"]),
        Station(id: "broadwayfairlawn", name: "Broadway Fair Lawn", plannerName: "Broadway Station Fair Lawn", shortLabel: "Broadway Fair Lawn", lines: ["BERG"]),
        Station(id: "campbellhall", name: "Campbell Hall", plannerName: "Campbell Hall Station", shortLabel: "Campbell Hall", lines: ["BERG", "MAIN"]),
        Station(id: "chatham", name: "Chatham", plannerName: "Chatham Station", shortLabel: "Chatham", lines: ["M&E"]),
        Station(id: "cherryhill", name: "Cherry Hill", plannerName: "Cherry Hill Station", shortLabel: "Cherry Hill", lines: ["ACRL"]),
        Station(id: "clifton", name: "Clifton", plannerName: "Clifton Station", shortLabel: "Clifton", lines: ["MAIN"]),
        Station(id: "conventstation", name: "Convent Station", plannerName: "Convent Station", shortLabel: "Convent Station", lines: ["M&E"]),
        Station(id: "cranford", name: "Cranford", plannerName: "Cranford Station", shortLabel: "Cranford", lines: ["RARV"]),
        Station(id: "delawanna", name: "Delawanna", plannerName: "Delawanna Station", shortLabel: "Delawanna", lines: ["MAIN"]),
        Station(id: "denville", name: "Denville", plannerName: "Denville Station", shortLabel: "Denville", lines: ["M&E", "MOBO"]),
        Station(id: "dover", name: "Dover", plannerName: "Dover Station", shortLabel: "Dover", lines: ["M&E", "MOBO"]),
        Station(id: "dunellen", name: "Dunellen", plannerName: "Dunellen Station", shortLabel: "Dunellen", lines: ["RARV"]),
        Station(id: "eastorange", name: "East Orange", plannerName: "East Orange Station", shortLabel: "East Orange", lines: ["M&E"]),
        Station(id: "edison", name: "Edison", plannerName: "Edison Station", shortLabel: "Edison", lines: ["NEC"]),
        Station(id: "eggharborcity", name: "Egg Harbor City", plannerName: "Egg Harbor City Station", shortLabel: "Egg Harbor City", lines: ["ACRL"]),
        Station(id: "elberon", name: "Elberon", plannerName: "Elberon Station", shortLabel: "Elberon", lines: ["NJCL"]),
        Station(id: "elizabeth", name: "Elizabeth", plannerName: "Elizabeth Station", shortLabel: "Elizabeth", lines: ["NEC", "NJCL"]),
        Station(id: "emerson", name: "Emerson", plannerName: "Emerson Station", shortLabel: "Emerson", lines: ["PASC"]),
        Station(id: "essexstreet", name: "Essex Street", plannerName: "Essex Street Station (PVL)", shortLabel: "Essex Street", lines: ["PASC"]),
        Station(id: "fanwood", name: "Fanwood", plannerName: "Fanwood Station", shortLabel: "Fanwood", lines: ["RARV"]),
        Station(id: "farhills", name: "Far Hills", plannerName: "Far Hills Station", shortLabel: "Far Hills", lines: ["M&E"]),
        Station(id: "garfield", name: "Garfield", plannerName: "Garfield Station", shortLabel: "Garfield", lines: ["BERG"]),
        Station(id: "garwood", name: "Garwood", plannerName: "Garwood Station", shortLabel: "Garwood", lines: ["RARV"]),
        Station(id: "gillette", name: "Gillette", plannerName: "Gillette Station", shortLabel: "Gillette", lines: ["M&E"]),
        Station(id: "gladstone", name: "Gladstone", plannerName: "Gladstone Station", shortLabel: "Gladstone", lines: ["M&E"]),
        Station(id: "glenridge", name: "Glen Ridge", plannerName: "Glen Ridge Station", shortLabel: "Glen Ridge", lines: ["MOBO"]),
        Station(id: "glenrockborohall", name: "Glen Rock Boro Hall", plannerName: "Glen Rock Boro Hall Station", shortLabel: "Glen Rock Boro Hall", lines: ["BERG"]),
        Station(id: "glenrockmainline", name: "Glen Rock Main Line", plannerName: "Glen Rock Main Line Station", shortLabel: "Glen Rock Main Line", lines: ["MAIN"]),
        Station(id: "hackettstown", name: "Hackettstown", plannerName: "Hackettstown Station", shortLabel: "Hackettstown", lines: ["M&E", "MOBO"]),
        Station(id: "hamilton", name: "Hamilton", plannerName: "Hamilton Station", shortLabel: "Hamilton", lines: ["NEC"]),
        Station(id: "hammonton", name: "Hammonton", plannerName: "Hammonton Station", shortLabel: "Hammonton", lines: ["ACRL"]),
        Station(id: "harriman", name: "Harriman", plannerName: "Harriman Station", shortLabel: "Harriman", lines: ["BERG", "MAIN"]),
        Station(id: "hawthorne", name: "Hawthorne", plannerName: "Hawthorne Station", shortLabel: "Hawthorne", lines: ["MAIN"]),
        Station(id: "hazlet", name: "Hazlet", plannerName: "Hazlet Station", shortLabel: "Hazlet", lines: ["NJCL"]),
        Station(id: "highbridge", name: "High Bridge", plannerName: "High Bridge Station", shortLabel: "High Bridge", lines: ["RARV"]),
        Station(id: "highlandavenue", name: "Highland Avenue", plannerName: "Highland Avenue Station", shortLabel: "Highland Avenue", lines: ["M&E"]),
        Station(id: "hillsdale", name: "Hillsdale", plannerName: "Hillsdale Station", shortLabel: "Hillsdale", lines: ["PASC"]),
        Station(id: "hoboken", name: "Hoboken", plannerName: "Hoboken Terminal", shortLabel: "Hoboken", lines: ["BERG", "M&E", "MAIN", "MOBO", "PASC"]),
        Station(id: "hohokus", name: "Hohokus", plannerName: "Ho-Ho-Kus Station", shortLabel: "Ho-Ho-Kus", lines: ["BERG", "MAIN"]),
        Station(id: "jerseyavenue", name: "Jersey Avenue", plannerName: "Jersey Avenue Station (Northeast Corridor)", shortLabel: "Jersey Avenue", lines: ["NEC"]),
        Station(id: "lakehopatcong", name: "Lake Hopatcong", plannerName: "Lake Hopatcong Station", shortLabel: "Lake Hopatcong", lines: ["M&E", "MOBO"]),
        Station(id: "lebanon", name: "Lebanon", plannerName: "Lebanon Station", shortLabel: "Lebanon", lines: ["RARV"]),
        Station(id: "lincolnpark", name: "Lincoln Park", plannerName: "Lincoln Park Station", shortLabel: "Lincoln Park", lines: ["MOBO"]),
        Station(id: "linden", name: "Linden", plannerName: "Linden Station", shortLabel: "Linden", lines: ["NEC", "NJCL"]),
        Station(id: "lindenwold", name: "Lindenwold", plannerName: "Lindenwold Station", shortLabel: "Lindenwold", lines: ["ACRL"]),
        Station(id: "littlefalls", name: "Little Falls", plannerName: "Little Falls Station", shortLabel: "Little Falls", lines: ["MOBO"]),
        Station(id: "littlesilver", name: "Little Silver", plannerName: "Little Silver Station", shortLabel: "Little Silver", lines: ["NJCL"]),
        Station(id: "longbranch", name: "Long Branch", plannerName: "Long Branch Station", shortLabel: "Long Branch", lines: ["NJCL"]),
        Station(id: "lyndhurst", name: "Lyndhurst", plannerName: "Lyndhurst Station", shortLabel: "Lyndhurst", lines: ["MAIN"]),
        Station(id: "lyons", name: "Lyons", plannerName: "Lyons Station", shortLabel: "Lyons", lines: ["M&E"]),
        Station(id: "madison", name: "Madison", plannerName: "Madison Station", shortLabel: "Madison", lines: ["M&E"]),
        Station(id: "mahwah", name: "Mahwah", plannerName: "Mahwah Station", shortLabel: "Mahwah", lines: ["BERG", "MAIN"]),
        Station(id: "manasquan", name: "Manasquan", plannerName: "Manasquan Station", shortLabel: "Manasquan", lines: ["NJCL"]),
        Station(id: "maplewood", name: "Maplewood", plannerName: "Maplewood Station", shortLabel: "Maplewood", lines: ["M&E"]),
        Station(id: "metropark", name: "Metropark", plannerName: "Metropark Station", shortLabel: "Metropark", lines: ["NEC"]),
        Station(id: "metuchen", name: "Metuchen", plannerName: "Metuchen Station", shortLabel: "Metuchen", lines: ["NEC"]),
        Station(id: "middletownnj", name: "Middletown NJ", plannerName: "Middletown New Jersey Station", shortLabel: "Middletown NJ", lines: ["NJCL"]),
        Station(id: "middletownny", name: "Middletown NY", plannerName: "Middletown New York Station", shortLabel: "Middletown NY", lines: ["BERG", "MAIN"]),
        Station(id: "millburn", name: "Millburn", plannerName: "Millburn Station", shortLabel: "Millburn", lines: ["M&E"]),
        Station(id: "millington", name: "Millington", plannerName: "Millington Station", shortLabel: "Millington", lines: ["M&E"]),
        Station(id: "montclairheights", name: "Montclair Heights", plannerName: "Montclair Heights Station", shortLabel: "Montclair Heights", lines: ["MOBO"]),
        Station(id: "montclairstateu", name: "Montclair State U", plannerName: "Montclair State University Station", shortLabel: "Montclair State U", lines: ["MOBO"]),
        Station(id: "montvale", name: "Montvale", plannerName: "Montvale Station", shortLabel: "Montvale", lines: ["PASC"]),
        Station(id: "morrisplains", name: "Morris Plains", plannerName: "Morris Plains Station", shortLabel: "Morris Plains", lines: ["M&E"]),
        Station(id: "morristown", name: "Morristown", plannerName: "Morristown Station", shortLabel: "Morristown", lines: ["M&E"]),
        Station(id: "mountarlington", name: "Mount Arlington", plannerName: "Mount Arlington Station", shortLabel: "Mount Arlington", lines: ["M&E", "MOBO"]),
        Station(id: "mountolive", name: "Mount Olive", plannerName: "Mount Olive Station", shortLabel: "Mount Olive", lines: ["M&E", "MOBO"]),
        Station(id: "mounttabor", name: "Mount Tabor", plannerName: "Mount Tabor Station", shortLabel: "Mount Tabor", lines: ["M&E"]),
        Station(id: "mountainavenue", name: "Mountain Avenue", plannerName: "Mountain Avenue Station", shortLabel: "Mountain Avenue", lines: ["MOBO"]),
        Station(id: "mountainlakes", name: "Mountain Lakes", plannerName: "Mountain Lakes Station", shortLabel: "Mountain Lakes", lines: ["MOBO"]),
        Station(id: "mountainstation", name: "Mountain Station", plannerName: "Mountain Station", shortLabel: "Mountain Station", lines: ["M&E"]),
        Station(id: "mountainview", name: "Mountain View", plannerName: "Mountain View Station", shortLabel: "Mountain View", lines: ["MOBO"]),
        Station(id: "murrayhill", name: "Murray Hill", plannerName: "Murray Hill Station", shortLabel: "Murray Hill", lines: ["M&E"]),
        Station(id: "nanuet", name: "Nanuet", plannerName: "Nanuet Station", shortLabel: "Nanuet", lines: ["PASC"]),
        Station(id: "netcong", name: "Netcong", plannerName: "Netcong Station", shortLabel: "Netcong", lines: ["M&E", "MOBO"]),
        Station(id: "netherwood", name: "Netherwood", plannerName: "Netherwood Station", shortLabel: "Netherwood", lines: ["RARV"]),
        Station(id: "newbridgelanding", name: "New Bridge Landing", plannerName: "New Bridge Landing Station", shortLabel: "New Bridge Landing", lines: ["PASC"]),
        Station(id: "newbrunswick", name: "New Brunswick", plannerName: "New Brunswick Station", shortLabel: "New Brunswick", lines: ["NEC"]),
        Station(id: "newprovidence", name: "New Providence", plannerName: "New Providence Station", shortLabel: "New Providence", lines: ["M&E"]),
        Station(id: "penn", name: "New York Penn Station", plannerName: "New York Penn Station", shortLabel: "New York Penn Station", lines: ["M&E", "MOBO", "NEC", "NJCL", "RARV"]),
        Station(id: "newarkairport", name: "Newark Airport", plannerName: "Newark Airport Rail Station", shortLabel: "Newark Airport", lines: ["NEC", "NJCL"]),
        Station(id: "newarkbroadstreet", name: "Newark Broad Street", plannerName: "Newark Broad Street Station", shortLabel: "Newark Broad St", lines: ["M&E", "MOBO"]),
        Station(id: "newarkpennstation", name: "Newark Penn Station", plannerName: "Newark Penn Station", shortLabel: "Newark Penn", lines: ["NEC", "NJCL", "RARV"]),
        Station(id: "northbranch", name: "North Branch", plannerName: "North Branch Station", shortLabel: "North Branch", lines: ["RARV"]),
        Station(id: "northelizabeth", name: "North Elizabeth", plannerName: "North Elizabeth Station", shortLabel: "North Elizabeth", lines: ["NEC", "NJCL"]),
        Station(id: "oradell", name: "Oradell", plannerName: "Oradell Station", shortLabel: "Oradell", lines: ["PASC"]),
        Station(id: "orange", name: "Orange", plannerName: "Orange Station", shortLabel: "Orange", lines: ["M&E"]),
        Station(id: "otisville", name: "Otisville", plannerName: "Otisville Station", shortLabel: "Otisville", lines: ["BERG", "MAIN"]),
        Station(id: "parkridge", name: "Park Ridge", plannerName: "Park Ridge Station", shortLabel: "Park Ridge", lines: ["PASC"]),
        Station(id: "passaic", name: "Passaic", plannerName: "Passaic Station", shortLabel: "Passaic", lines: ["MAIN"]),
        Station(id: "paterson", name: "Paterson", plannerName: "Paterson Station", shortLabel: "Paterson", lines: ["MAIN"]),
        Station(id: "peapack", name: "Peapack", plannerName: "Peapack Station", shortLabel: "Peapack", lines: ["M&E"]),
        Station(id: "pearlriver", name: "Pearl River", plannerName: "Pearl River Station", shortLabel: "Pearl River", lines: ["PASC"]),
        Station(id: "pennsauken", name: "Pennsauken", plannerName: "Pennsauken Transit Center Station", shortLabel: "Pennsauken", lines: ["ACRL"]),
        Station(id: "perthamboy", name: "Perth Amboy", plannerName: "Perth Amboy Station", shortLabel: "Perth Amboy", lines: ["NJCL"]),
        Station(id: "philadelphia", name: "Philadelphia", plannerName: "Philadelphia 30th Street Station", shortLabel: "Philadelphia", lines: ["ACRL"]),
        Station(id: "plainfield", name: "Plainfield", plannerName: "Plainfield Station", shortLabel: "Plainfield", lines: ["RARV"]),
        Station(id: "plauderville", name: "Plauderville", plannerName: "Plauderville Station", shortLabel: "Plauderville", lines: ["BERG"]),
        Station(id: "pointpleasantbeach", name: "Point Pleasant Beach", plannerName: "Point Pleasant Beach Station", shortLabel: "Point Pleasant Beach", lines: ["NJCL"]),
        Station(id: "portjervis", name: "Port Jervis", plannerName: "Port Jervis Station", shortLabel: "Port Jervis", lines: ["BERG", "MAIN"]),
        Station(id: "princeton", name: "Princeton", plannerName: "Princeton Station", shortLabel: "Princeton", lines: ["PRIN"]),
        Station(id: "princetonjunction", name: "Princeton Junction", plannerName: "Princeton Junction Station", shortLabel: "Princeton Junction", lines: ["NEC", "PRIN"]),
        Station(id: "radburnfairlawn", name: "Radburn Fair Lawn", plannerName: "Radburn Station", shortLabel: "Radburn Fair Lawn", lines: ["BERG"]),
        Station(id: "rahway", name: "Rahway", plannerName: "Rahway Station", shortLabel: "Rahway", lines: ["NEC", "NJCL"]),
        Station(id: "ramseymainst", name: "Ramsey Main St", plannerName: "Ramsey Main Street Station", shortLabel: "Ramsey Main St", lines: ["BERG", "MAIN"]),
        Station(id: "ramseyroute17", name: "Ramsey Route 17", plannerName: "Ramsey Route 17 Station", shortLabel: "Ramsey Route 17", lines: ["BERG", "MAIN"]),
        Station(id: "raritan", name: "Raritan", plannerName: "Raritan Station", shortLabel: "Raritan", lines: ["RARV"]),
        Station(id: "redbank", name: "Red Bank", plannerName: "Red Bank Station", shortLabel: "Red Bank", lines: ["NJCL"]),
        Station(id: "ridgewood", name: "Ridgewood", plannerName: "Ridgewood Station", shortLabel: "Ridgewood", lines: ["BERG", "MAIN"]),
        Station(id: "riveredge", name: "River Edge", plannerName: "River Edge Station", shortLabel: "River Edge", lines: ["PASC"]),
        Station(id: "rosellepark", name: "Roselle Park", plannerName: "Roselle Park Station", shortLabel: "Roselle Park", lines: ["RARV"]),
        Station(id: "rutherford", name: "Rutherford", plannerName: "Rutherford Station", shortLabel: "Rutherford", lines: ["BERG"]),
        Station(id: "salisburymillscornwall", name: "Salisbury Mills-Cornwall", plannerName: "Salisbury Mills Cornwall Station", shortLabel: "Salisbury Mills-Cornwall", lines: ["BERG", "MAIN"]),
        Station(id: "secaucus", name: "Secaucus", plannerName: "Secaucus Junction Station", shortLabel: "Secaucus", lines: ["BERG", "M&E", "MAIN", "MOBO", "NEC", "NJCL", "PASC", "RARV"]),
        Station(id: "shorthills", name: "Short Hills", plannerName: "Short Hills Station", shortLabel: "Short Hills", lines: ["M&E"]),
        Station(id: "sloatsburg", name: "Sloatsburg", plannerName: "Sloatsburg Station", shortLabel: "Sloatsburg", lines: ["BERG", "MAIN"]),
        Station(id: "somerville", name: "Somerville", plannerName: "Somerville Station", shortLabel: "Somerville", lines: ["RARV"]),
        Station(id: "southamboy", name: "South Amboy", plannerName: "South Amboy Station", shortLabel: "South Amboy", lines: ["NJCL"]),
        Station(id: "southorange", name: "South Orange", plannerName: "South Orange Station", shortLabel: "South Orange", lines: ["M&E"]),
        Station(id: "springlake", name: "Spring Lake", plannerName: "Spring Lake Station", shortLabel: "Spring Lake", lines: ["NJCL"]),
        Station(id: "springvalley", name: "Spring Valley", plannerName: "Spring Valley Station", shortLabel: "Spring Valley", lines: ["PASC"]),
        Station(id: "stirling", name: "Stirling", plannerName: "Stirling Station", shortLabel: "Stirling", lines: ["M&E"]),
        Station(id: "suffern", name: "Suffern", plannerName: "Suffern Station", shortLabel: "Suffern", lines: ["BERG", "MAIN"]),
        Station(id: "summit", name: "Summit", plannerName: "Summit Station", shortLabel: "Summit", lines: ["M&E"]),
        Station(id: "teterboro", name: "Teterboro", plannerName: "Teterboro Station", shortLabel: "Teterboro", lines: ["PASC"]),
        Station(id: "towaco", name: "Towaco", plannerName: "Towaco Station", shortLabel: "Towaco", lines: ["MOBO"]),
        Station(id: "trenton", name: "Trenton", plannerName: "Trenton Transit Center", shortLabel: "Trenton", lines: ["NEC"]),
        Station(id: "tuxedo", name: "Tuxedo", plannerName: "Tuxedo Station", shortLabel: "Tuxedo", lines: ["BERG", "MAIN"]),
        Station(id: "union", name: "Union", plannerName: "Union Station", shortLabel: "Union", lines: ["RARV"]),
        Station(id: "uppermontclair", name: "Upper Montclair", plannerName: "Upper Montclair Station", shortLabel: "Upper Montclair", lines: ["MOBO"]),
        Station(id: "waldwick", name: "Waldwick", plannerName: "Waldwick Station", shortLabel: "Waldwick", lines: ["BERG", "MAIN"]),
        Station(id: "walnutstreet", name: "Walnut Street", plannerName: "Walnut Street Station", shortLabel: "Walnut Street", lines: ["MOBO"]),
        Station(id: "watchung", name: "Watchung Avenue", plannerName: "Watchung Avenue Station", shortLabel: "Watchung Avenue", lines: ["MOBO"]),
        Station(id: "watsessingavenue", name: "Watsessing Avenue", plannerName: "Watsessing Avenue Station", shortLabel: "Watsessing Avenue", lines: ["MOBO"]),
        Station(id: "wayneroute23", name: "Wayne-Route 23", plannerName: "Wayne-Route 23 Transit Center Rail Station", shortLabel: "Wayne-Rt 23", lines: ["MOBO"]),
        Station(id: "wesmont", name: "Wesmont", plannerName: "Wesmont Station", shortLabel: "Wesmont", lines: ["BERG"]),
        Station(id: "westfield", name: "Westfield", plannerName: "Westfield Station", shortLabel: "Westfield", lines: ["RARV"]),
        Station(id: "westwood", name: "Westwood", plannerName: "Westwood Station", shortLabel: "Westwood", lines: ["PASC"]),
        Station(id: "whitehouse", name: "White House", plannerName: "White House Station", shortLabel: "White House", lines: ["RARV"]),
        Station(id: "woodridge", name: "Wood Ridge", plannerName: "Wood Ridge Station", shortLabel: "Wood Ridge", lines: ["PASC"]),
        Station(id: "woodbridge", name: "Woodbridge", plannerName: "Woodbridge Station", shortLabel: "Woodbridge", lines: ["NJCL"]),
        Station(id: "woodclifflake", name: "Woodcliff Lake", plannerName: "Woodcliff Lake Station", shortLabel: "Woodcliff Lake", lines: ["PASC"]),
    ]
}
